config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#welcome'

  get "/home", to: 'users#home'

  get "/login", to: 'sessions#new'
  post "/sessions", to: 'sessions#create'
  get "/logout", to: 'sessions#destroy'

  get "/signup", to: 'users#new'
  post "/users", to: 'users#create'
  get '/edit', to: 'users#edit'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'


  get "/movies", to: 'movies#index'
  get "/movies/new", to: 'movies#new', as: "new_movie"
  post "/movies", to: 'movies#create'
  get "/movies/:movie", to: 'movies#show', as: "movie"
  get "/movies/:movie/edit", to: 'movies#edit', as: "edit_movie"
  patch "/movies/:movie", to: 'movies#update'
  get "/movies/:movie/:group", to: 'movies#show_group_filter', as: "movie_group"
  delete '/movies/:movie', to: 'movies#destroy'


  get "/groups", to: 'groups#index'
  get "/groups/new", to: 'groups#new', as: "new_group"
  post "/groups", to: 'groups#create'
  get "/groups/:group", to: 'groups#show', as: "group"
  get "/groups/:group/edit", to: 'groups#edit', as: "edit_group"
  patch "/groups/:group", to: 'groups#update'
  get "/groups/:group/:movie", to: 'groups#show_movie_filter', as: "group_movie"
  delete '/groups/:group', to: 'groups#destroy'
  post "join", to: 'groups#join', as: "join_group"
  post "leave", to: 'groups#leave', as: "leave_group"

  get "/comments/:id", to: 'comments#show', as: "comment"
  post "/comments", to: 'comments#create'
  patch "/comments/:id", to: 'comments#update'
  delete "/comments/:id", to: 'comments#destroy'
  post "/vote", to: 'comments#vote', as: "vote"

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(params[:name])

    if @movie.valid?
      @movie.save
    else
      flash[:error] = @movie.errors.full_messages
      redirect_to movie_path
    end
  end

  def show
    @user = current_user
    @movie = Movie.find(params[:movie])
    @comments = @movie.visible_comment_trees(@user.id)
    @vote = Comment.new
    @groups = @user.groups
    @new_comment = Comment.new
  end

  def index
    @user = current_user
    @my_movies = Movie.all.select{ |movie|
      movie.groups.any?{ |group|
        group.user_ids.include?(@user.id)}}

    @other_movies = Movie.all.reject{ |movie| movie.groups.any?{ |group| group.user_ids.include?(@user.id)}}
  end

end

app/views/movies/_comment.html.erb
<% if !comment.parent_id %>
<div class=parent_comment>
  <div class=up>▲</div>
  <div class=down>▼</div>
  <div class=comment_rating>
    <span class=rating><%= comment.get_rating %></span>
  </div>
  <div class=comment_content>
  <%= comment.content %>
  <div class=comment_info>
    <%= comment.time_since_created %>
    by <%= link_to comment.user.name, user_path(comment.user), { class: "comment_link" } %>
    to <%= link_to comment.group.name, group_path(comment.group), { class: "comment_link" } %>
    about <%= link_to comment.movie.name, movie_path(comment.movie), { class: "comment_link" } %>
    - <%= comment.children_that_are_not_votes.length %> replies
    -
    <a href="javascript:showhide('<%= "reply" + comment.id.to_s %>')" class="add_comment">
        reply
    </a>
  </div>
  </div>
  <div id= <%= "reply" + comment.id.to_s %> class="magic">
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.number_field :group_movie_id, value: comment.group_movie_id, type: :hidden %>
    <%= f.label :"vote_+1", "+1"%>
    <%= f.radio_button :vote, "+1", checked: 1 %>
    <%= f.label :"vote_-1", "-1"%>
    <%= f.radio_button :vote, "-1", checked: -1 %>
    <%= f.number_field :parent_id, value: comment.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %>
    <%= f.submit %>
    <% end %>
  </div>
</div>



<% else %>
<div class=comment>
  <div class=up>▲</div>
  <div class=down>▼</div>
  <div class=comment_rating>
    <%= comment.get_rating %>
  </div>
  <div class=comment_content>
  <%= comment.content %>
  <div class=comment_info>
    <%= comment.time_since_created %>
    by <%= link_to comment.user.name, user_path(comment.user), { class: "comment_link" } %>
    to <%= link_to comment.group.name, group_path(comment.group), { class: "comment_link" } %>
    about <%= link_to comment.movie.name, movie_path(comment.movie), { class: "comment_link" } %>
    - <%= comment.children_that_are_not_votes.length %> replies
    -
    <a href="javascript:showhide('<%= "reply" + comment.id.to_s %>')" class="add_comment">
        reply
    </a>
  </div>
  </div>
  <div id= <%= "reply" + comment.id.to_s %> class="magic">
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.number_field :group_movie_id, value: comment.group_movie_id, type: :hidden %>
    <%= f.label :"vote_+1", "+1"%>
    <%= f.radio_button :vote, "+1", checked: 1 %>
    <%= f.label :"vote_-1", "-1"%>
    <%= f.radio_button :vote, "-1", checked: -1 %>
    <%= f.number_field :parent_id, value: comment.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %>
    <%= f.submit %>
    <% end %>
  </div>
</div>
<% end %>

app/views/movies/_comments.html.erb
<div class=all_comments>
  <% if !@groups.empty? %>
    <div class=message>
    <% if flash[:error] %>
      <%flash[:error].each do |message|%>
        <%= message %></br>
      <% end %>
    <% end %>
    </div>
  <div class=new_comment>
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %>
    To Group:
    <%= f.collection_select :group, @groups, :id, :name, prompt: true %>
    <%= f.number_field :movie, value: @movie.id, type: :hidden %>
    <%= f.number_field :vote, value: 1, type: :hidden %>
    <%= f.number_field :parent_id, value: nil, type: :hidden %>
    <%= f.submit %>
    <% end %>
  </div>
  <% end %>
    <%= plant_trees_for @comments %>
</div>


<% if @comments == [] %>
<div class=no_comments_container>
  <div class=no_comments>
  <p>
  No comments <br />
  to view... <br />
  <span id=yet> YET! </span><br />
  Join a Group,<br />
  make some <br /> Movie Friends!
  </p>
  </div>
</div>
<% end %>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <%= f.text_field :name, placeholder: "Name" %><br />
  <%= f.file_field :picture, id: :movie_picture %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/movies/_form0.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: "Name", class: 'session' %><br />
  <%= f.file_field :picture, id: :user_picture %>
  <%= f.submit "Sign Up", class: 'session'  %>
<% end %>

app/views/movies/_lil_logo.html.erb
<div class=lil_logo_container>
<div class=lil_logo>
<%= render 'logo' %>
</div>
</div>

app/views/movies/_logo.html.erb
<div class='movie_friends'>
  <div class='i_left'>
    i
  </div>
  <div class='i_right'>
    i
  </div>
  <div class='movie'>
    <span class='purple'>M</span><span class='o_class'>O</span><span class='red'>V</span><span class='green'>I</span><span class='orange'>e</span>
  </div>
  <div class='friends'>
    <span class='blue'>F</span><span class='red'>R</span><span class='orange'>i</span><span class='green'>E</span><span class='purple'>N</span><span class='blue'>D</span><span class='yellow'>s</span>
  </div>
</div>

app/views/movies/_menu.html.erb
<div class="menu">
  <%= link_to "Home", home_path, id: 'menu_home'%> |
  <%= link_to "Movies", movies_path, id: 'menu_movies'%> |
  <%= link_to "Groups", groups_path, id: 'menu_groups' %> |
  <%= link_to "Sign Out", logout_path, id: 'menu_signout' %>
</div>

app/views/movies/index.html.erb
<!-- List of movies in your groups -->
<%= render 'lil_logo' %>
<%= render 'menu' %>

<div class=all_comments>
<center><span class=page_title>Your Movies:</span></center>

<div class=my_movies>
  <% if @my_movies.empty? %>
    <center>You have not joined any Groups yet!</center>
  <% end %>
<% @my_movies.each do |movie| %>
  <div class=movie_container>
  <span class=movie_name>
    <%= link_to movie.name, movie_path(movie) %>
  </span><br /><br />
  <span class=movie_group_names>
    Groups:
    <% movie.user_groups(@user.id).each do |group| %>
      <%= link_to group.name, group_movie_path(group, movie) %>
    <% end %>
  </span>
  </div>
<% end %>

</div>

<center><span class=page_title>Other Movies:</span></center>

<div class=other_movies>

<% @other_movies.each do |movie| %>

<div class=movie_container>
  <span class=movie_name>
    <%= link_to movie.name, movie_path(movie) %>
  </span><br /><br />
  <span class=movie_group_names>
    Groups:
    <% movie.groups.each do |group| %>
      <%= link_to group.name, group_movie_path(group, movie) %>
    <% end %>
  </span>
  </div>

<% end %>

</div>
</div>

<div class='content'>
</div>



<!-- List of all movies available from all groups -->

app/views/movies/show.html.erb
 <%= render 'lil_logo' %>
 <%= render 'menu' %>
 <%= render 'comments' %>

 <div class=message>
 <% if flash[:error] %>
   <%flash[:error].each do |message|%>
     <%= message %></br>
   <% end %>
 <% end %>
 </div>

 <div class='content'>
Movie Title and image

discussion box all comments relating to movie from all of your group_path
     OR
     A form avaiable to create a new post with group selector
 </div>