config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#welcome'

  get "/home", to: 'users#home'

  get "/login", to: 'sessions#new'
  post "/sessions", to: 'sessions#create'
  get "/logout", to: 'sessions#destroy'

  get "/signup", to: 'users#new'
  post "/users", to: 'users#create'
  get '/edit', to: 'users#edit'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'


  get "/movies", to: 'movies#index'
  get "/movies/new", to: 'movies#new', as: "new_movie"
  post "/movies", to: 'movies#create'
  get "/movies/:movie", to: 'movies#show', as: "movie"
  get "/movies/:movie/edit", to: 'movies#edit', as: "edit_movie"
  patch "/movies/:movie", to: 'movies#update'
  get "/movies/:movie/:group", to: 'movies#show_group_filter', as: "movie_group"
  delete '/movies/:movie', to: 'movies#destroy'


  get "/groups", to: 'groups#index'
  get "/groups/new", to: 'groups#new', as: "new_group"
  post "/groups", to: 'groups#create'
  get "/groups/:group", to: 'groups#show', as: "group"
  get "/groups/:group/edit", to: 'groups#edit', as: "edit_group"
  patch "/groups/:group", to: 'groups#update'
  get "/groups/:group/:movie", to: 'groups#show_movie_filter', as: "group_movie"
  delete '/groups/:group', to: 'groups#destroy'
  post "join", to: 'groups#join', as: "join_group"
  post "leave", to: 'groups#leave', as: "leave_group"

  get "/comments/:id", to: 'comments#show', as: "comment"
  post "/comments", to: 'comments#create'
  patch "/comments/:id", to: 'comments#update'
  delete "/comments/:id", to: 'comments#destroy'
  post "/vote", to: 'comments#vote', as: "vote"

end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :memberships
  has_many :users, through: :memberships
  belongs_to :admin, class_name: "User"

  has_many :group_movies
  has_many :movies, through: :group_movies
  has_many :comments, through: :group_movies
  

  validates :name, uniqueness: true

  def visible_comment_trees
    self.comments.select {|comment| comment.parent_id == nil && comment.content != nil}.sort_by {|comment| comment.updated_at}.reverse.map(&:make_tree)
  end

  def add_user(user)
    if !self.users.include?(user)
      self.users << user
    else
      return false
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.valid?
      @group.save
      @group.users << current_user
      redirect_to group_path(@group.id)
    else
      flash[:error] = @group.errors.full_messages
      redirect_to groups_path
    end
  end

  def show
    @user = current_user
    @group = Group.find(params[:group])
    @comments = @group.visible_comment_trees
    @vote = Comment.new
    @new_comment = Comment.new
    @movies = Movie.all

  end

  def index
    @user = current_user
    @my_groups = @user.groups
    @all_groups = Group.all.select {|g| !g.users.include?(@user)}
    @vote = Comment.new
    @new_comment = Comment.new
    @new_group = Group.new
  end

  def join
    @user = current_user
    group = Group.find(params[:group][:id])
    if group.add_user(@user)
    else
      flash[:error] = "User already included in group"
    end
    redirect_to group_path(group)
  end

  def leave
    @user = current_user
    group = Group.find(params[:group][:id])
    membership = Membership.find_by(user: @user, group: group)
    membership.destroy
    redirect_to request.referrer
  end

  def show_movie_filter
    @user = current_user
    @group = Group.find(params[:group])
    @movie = Movie.find(params[:movie])
    group_movie = GroupMovie.find_by(group_id: params[:group], movie_id: params[:movie])
    @comments = group_movie.visible_comment_trees
    @new_comment = Comment.new
    @vote = Comment.new
  end

  private
    def group_params
      params.require(:group).permit(:name, :admin_id)
    end

end

app/views/groups/_comment.html.erb
<% if !comment.parent_id %>
<div class=parent_comment>
  <div class=comment_rating>
    <span class=rating><%= comment.get_rating %></span>
  </div>
  <div class=comment_content>
  <%= comment.content %>
  <div class=comment_info>
    <%= comment.time_since_created %>
    by <%= link_to comment.user.name, user_path(comment.user), { class: "comment_link" } %>
    to <%= link_to comment.group.name, group_path(comment.group), { class: "comment_link" } %>
    about <%= link_to comment.movie.name, movie_path(comment.movie), { class: "comment_link" } %>
    - <%= comment.children_that_are_not_votes.length %> replies
    -
    <a href="javascript:showhide('<%= "reply" + comment.id.to_s %>')" class="add_comment">
        reply
    </a>
  </div>
  </div>
  <div id= <%= "reply" + comment.id.to_s %> class="magic">
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.number_field :group_movie_id, value: comment.group_movie_id, type: :hidden %>
    <%= f.label :"vote_+1", "+1"%>
    <%= f.radio_button :vote, "+1", checked: 1 %>
    <%= f.label :"vote_-1", "-1"%>
    <%= f.radio_button :vote, "-1", checked: -1 %>
    <%= f.number_field :parent_id, value: comment.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %>
    <%= f.submit %>
    <% end %>
  </div>
</div>



<% else %>
<div class=comment>
  <div class=up>▲</div>
  <div class=down>▼</div>
  <div class=comment_rating>
    <%= comment.get_rating %>
  </div>
  <div class=comment_content>
  <%= comment.content %>
  <div class=comment_info>
    <%= comment.time_since_created %>
    by <%= link_to comment.user.name, user_path(comment.user), { class: "comment_link" } %>
    to <%= link_to comment.group.name, group_path(comment.group), { class: "comment_link" } %>
    about <%= link_to comment.movie.name, movie_path(comment.movie), { class: "comment_link" } %>
    - <%= comment.children_that_are_not_votes.length %> replies
    -
    <a href="javascript:showhide('<%= "reply" + comment.id.to_s %>')" class="add_comment">
        reply
    </a>
  </div>
  </div>
  <div id= <%= "reply" + comment.id.to_s %> class="magic">
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.number_field :group_movie_id, value: comment.group_movie_id, type: :hidden %>
    <%= f.label :"vote_+1", "+1"%>
    <%= f.radio_button :vote, "+1", checked: 1 %>
    <%= f.label :"vote_-1", "-1"%>
    <%= f.radio_button :vote, "-1", checked: -1 %>
    <%= f.number_field :parent_id, value: comment.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %>
    <%= f.submit %>
    <% end %>
  </div>
</div>
<% end %>

app/views/groups/_comments.html.erb
<div class=all_comments>
  <% if @group.users.include?(@user) %>
    
  <div class=new_comment>
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %>
    <% if !@movie %>
    About Movie:
    <%= f.collection_select :movie, @movies, :id, :name, prompt: true %>
    <% else %>
    <%= f.number_field :movie, value: @movie.id, type: :hidden %>
    <% end %>
    <%= f.number_field :group, value: @group.id, type: :hidden %>
    <%= f.number_field :vote, value: 1, type: :hidden %>
    <%= f.number_field :parent_id, value: nil, type: :hidden %>
    <%= f.submit %>
    <% end %>
  </div>
  <% end %>
    <%= plant_trees_for @comments %>
</div>

<% if @comments == [] %>
<div class=no_comments_container>
  <div class=no_comments>
  <p>
  No comments <br />
  to view... <br />
  <span id=yet> YET! </span><br />
  Join a Group,<br />
  make some <br /> Movie Friends!
  </p>
  </div>
</div>
<% end %>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= f.text_field :name, placeholder: "Name" %><br />
  <%= f.file_field :picture, id: :group_picture %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/groups/_lil_logo.html.erb
<div class=lil_logo_container>
<div class=lil_logo>
<%= render 'logo' %>
</div>
</div>

app/views/groups/_menu.html.erb
<div class="menu">
  <%= link_to "Home", home_path, id: 'menu_home'%> |
  <%= link_to "Movies", movies_path, id: 'menu_movies'%> |
  <%= link_to "Groups", groups_path, id: 'menu_groups' %> |
  <%= link_to "Sign Out", logout_path, id: 'menu_signout' %>
</div>

app/views/groups/index.html.erb
<%= render 'lil_logo' %>
<%= render 'menu' %>

<div class=all_comments>
<center><span class=page_title>Your Groups:</span></center>

<div class=my_movies>

<% if @my_groups.empty? %>
  <center>You have not joined any Groups yet!</center>
<% end %>

<% @my_groups.each do |group| %>

  <div class=movie_container>
  <span class=movie_name>
    <%= link_to group.name, group_path(group) %>
  </span><br /><br />
  <span class=movie_group_names>
    Movies:
    <% group.movies.each do |movie| %>
      <%= link_to movie.name, group_movie_path(group, movie) %>
    <% end %>
  </span>
  </div>

<% end %>

</div>

<center><span class=page_title>Other Groups:</span></center>

<div class=other_movies>

<% @all_groups.each do |group| %>

<div class=movie_container>
  <span class=movie_name>
    <%= link_to group.name, group_path(group) %>
  </span><br /><br />
  <span class=movie_group_names>
    Movies:
    <% group.movies.each do |movie| %>
      <%= link_to movie.name, group_movie_path(group, movie) %>
    <% end %>
  </span>
  </div>

<% end %>

</div>
</div>

<div class='content'>
Create a New Group:<br /><br />
<%= form_for @new_group do |f| %>
<%= f.text_field :name, placeholder: "Group Name" %><br />
<%= f.number_field :admin_id, value: @user.id, type: :hidden %><br />
<%= f.submit %>
<% end %>
</div>

app/views/groups/new.html.erb
<%= render 'logo' %>

<%= render 'form' %>

app/views/groups/show.html.erb
<%= render 'lil_logo' %>
<%= render 'menu' %>
<%= render 'comments' %>

<div class=message>
<% if flash[:error] %>
  <%flash[:error].each do |message|%>
    <%= message %></br>
  <% end %>
<% end %>
</div>

<div class='content'>
  <h1><%= @group.name %></h1>

  <h3>Members</h3>
    <% @group.users.each do |user| %>
      <%= link_to user.name, user_path(user.id) %><br />
    <% end %>
  <% if @group.users.include?(@user) %>
  <%= button_to "Leave Group", leave_group_path, params: {'group[id]' => @group.id} %>
  <% else %>
  <%= button_to "Join", join_group_path, params: {'group[id]' => @group.id} %>
  <% end %>
</div>

app/views/groups/show_movie_filter.html.erb
<%= render 'lil_logo' %>
<%= render 'menu' %>
<%= render 'comments' %>

<div class=message>
<% if flash[:error] %>
  <%flash[:error].each do |message|%>
    <%= message %></br>
  <% end %>
<% end %>
</div>

<div class='content'>
<h1><%= @group.name %> | <%= @movie.name %></h1>

<h3>Members</h3>
  <% @group.users.each do |user| %>
    <%= link_to user.name, user_path(user.id) %><br />
  <% end %>
<% if @group.users.include?(@user) %>
<%= button_to "Leave Group", leave_group_path, params: {'group[id]' => @group.id} %>
<% else %>
<%= button_to "Join", join_group_path, params: {'group[id]' => @group.id} %>
<% end %>
</div>