config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#welcome'

  get "/home", to: 'users#home'

  get "/login", to: 'sessions#new'
  post "/sessions", to: 'sessions#create'
  get "/logout", to: 'sessions#destroy'

  get "/signup", to: 'users#new'
  post "/users", to: 'users#create'
  get '/edit', to: 'users#edit'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'


  get "/movies", to: 'movies#index'
  get "/movies/new", to: 'movies#new', as: "new_movie"
  post "/movies", to: 'movies#create'
  get "/movies/:movie", to: 'movies#show', as: "movie"
  get "/movies/:movie/edit", to: 'movies#edit', as: "edit_movie"
  patch "/movies/:movie", to: 'movies#update'
  get "/movies/:movie/:group", to: 'movies#show_group_filter', as: "movie_group"
  delete '/movies/:movie', to: 'movies#destroy'


  get "/groups", to: 'groups#index'
  get "/groups/new", to: 'groups#new', as: "new_group"
  post "/groups", to: 'groups#create'
  get "/groups/:group", to: 'groups#show', as: "group"
  get "/groups/:group/edit", to: 'groups#edit', as: "edit_group"
  patch "/groups/:group", to: 'groups#update'
  get "/groups/:group/:movie", to: 'groups#show_movie_filter', as: "group_movie"
  delete '/groups/:group', to: 'groups#destroy'
  post "join", to: 'groups#join', as: "join_group"
  post "leave", to: 'groups#leave', as: "leave_group"

  get "/comments/:id", to: 'comments#show', as: "comment"
  post "/comments", to: 'comments#create'
  patch "/comments/:id", to: 'comments#update'
  delete "/comments/:id", to: 'comments#destroy'
  post "/vote", to: 'comments#vote', as: "vote"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  mount_uploader :picture, PictureUploader
  validates :name, presence: true, uniqueness: true
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :comments
  has_many :admin_groups, class_name: "Group", foreign_key: "admin_id"
  has_many :movies, through: :groups

  validates :name, uniqueness: true

  def get_user_groups_comments
    result = []

    self.groups.each do |group|
      result << group.comments
    end

    result.flatten!
    result.sort_by {|r| r.updated_at}
  end

  def available_movies
    movies = Hash.new
    self.groups.each do |group|
      movies[group_id] << group.movies
    end
    movies
  end

  def get_all_comment_trees_visible_by_user
    self.groups.map(&:visible_comment_trees).flatten.sort_by {|comment_tree| comment_tree[:comment][:updated_at]}.reverse
  end

  def get_user_comment_trees
    self.comments.select {|comment| comment.parent_id == nil && comment.content != nil}.sort_by {|comment| comment.updated_at}.reverse.map(&:make_tree)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def home
    @user = current_user
    @comments = current_user.get_all_comment_trees_visible_by_user
    @vote = Comment.new
    @new_comment = Comment.new
    @movies = Movie.all
    @groups = @user.groups
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      flash[:error] = @user.errors.full_messages
      redirect_to signup_path
    end
  end

  def update
    @user = User.find(params[:id])

    if !@user.authenticate(params[:user][:password])
      flash[:error] = ["Incorrect Password"]
      redirect_to user_path(@user.id)
    elsif @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to user_path(@user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.get_user_comment_trees
    @new_comment = Comment.new
    @vote = Comment.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :picture, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def grow(trees)
    trees.map do |key, value|
          case key
          when :comment
            render(partial: "/users/comment.html.erb", locals: {comment: value})
          else
            if value
              content_tag(:div, plant_trees_for(value), class: "replies")
            end
          end
        end
  end

def plant_trees_for(comments)
  comments.map do |comment|
    grow(comment)
  end.join.html_safe
end

end #mod end

app/views/users/_comment.html.erb
<% if !comment.parent_id %>
<div class=parent_comment>
  <div class=up>
    <%=link_to "▲", vote_path(parent_id: comment.id, vote: 1, content: nil), method: :post %>
  </div>
  <div class=down>
    <span class=down_link>
    <%=link_to "▼", vote_path(parent_id: comment.id, vote: -1, content: nil), method: :post%>
    </span>
  </div>
  <div class=comment_rating>
    <span class=rating><%= comment.get_rating %></span>
  </div>
  <div class=comment_content>
  <%= comment.content %>
  <div class=comment_info>
    <%= comment.time_since_created %>
    by <%= link_to comment.user.name, user_path(comment.user), { class: "comment_link" } %>
    to <%= link_to comment.group.name, group_path(comment.group), { class: "comment_link" } %>
    about <%= link_to comment.movie.name, movie_path(comment.movie), { class: "comment_link" } %>
    - <%= comment.children_that_are_not_votes.length %> replies
    -
    <a href="javascript:showhide('<%= "reply" + comment.id.to_s %>')" class="add_comment">
        reply
    </a>
  </div>
  </div>
  <div id= <%= "reply" + comment.id.to_s %> class="magic">
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.number_field :group_movie_id, value: comment.group_movie_id, type: :hidden %>
    <%= f.number_field :parent_id, value: comment.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %><br />
    <%= f.label :"vote_+1", "+1"%>
    <%= f.radio_button :vote, "+1", checked: 1 %>
    <%= f.label :"vote_-1", "-1"%>
    <%= f.radio_button :vote, "-1", checked: -1 %>
    <%= f.submit %>
    <% end %>
  </div>
</div>



<% else %>
<div class=comment>
  <div class=up>
    <%=link_to "▲", vote_path(parent_id: comment.id, vote: 1, content: nil), method: :post %>
  </div>
  <div class=down>
    <%=link_to "▼", vote_path(parent_id: comment.id, vote: -1, content: nil), method: :post %>
  </div>
  <div class=comment_rating>
    <%= comment.get_rating %>
  </div>
  <div class=comment_content>
  <%= comment.content %>
  <div class=comment_info>
    <%= comment.time_since_created %>
    by <%= link_to comment.user.name, user_path(comment.user), { class: "comment_link" } %>
    to <%= link_to comment.group.name, group_path(comment.group), { class: "comment_link" } %>
    about <%= link_to comment.movie.name, movie_path(comment.movie), { class: "comment_link" } %>
    - <%= comment.children_that_are_not_votes.length %> replies
    -
    <a href="javascript:showhide('<%= "reply" + comment.id.to_s %>')" class="add_comment">
        reply
    </a>
  </div>
  </div>
  <div id= <%= "reply" + comment.id.to_s %> class="magic">
    <%= form_for @new_comment do |f| %>
    <%= f.number_field :user_id, value: @user.id, type: :hidden %>
    <%= f.number_field :group_movie_id, value: comment.group_movie_id, type: :hidden %>
    <%= f.number_field :parent_id, value: comment.id, type: :hidden %>
    <%= f.text_field :content, placeholder: "Opinion!" %><br />
    <%= f.label :"vote_+1", "+1"%>
    <%= f.radio_button :vote, "+1", checked: 1 %>
    <%= f.label :"vote_-1", "-1"%>
    <%= f.radio_button :vote, "-1", checked: -1 %>
    <%= f.submit %>
    <% end %>
  </div>
</div>
<% end %>

app/views/users/_comments.html.erb
  <div class=all_comments>
    <% if !@groups.empty? %>
      <div class=message>
      <% if flash[:error] %>
        <%flash[:error].each do |message|%>
          <%= message %></br>
        <% end %>
      <% end %>
      </div>
    <div class=new_comment>
      <%= form_for @new_comment do |f| %>
      <%= f.number_field :user_id, value: @user.id, type: :hidden %>
      <%= f.text_field :content, placeholder: "Opinion!" %><br />
      About Movie:
      <%= f.collection_select :movie, @movies, :id, :name, prompt: true %>
      To Group:
      <%= f.collection_select :group, @groups, :id, :name, prompt: true %>
      <%= f.number_field :vote, value: 1, type: :hidden %>
      <%= f.number_field :parent_id, value: nil, type: :hidden %>
      <%= f.submit %>
      <% end %>
    </div>
    <% end %>
      <%= plant_trees_for @comments %>
  </div>

<% if @comments == [] %>
<div class=no_comments_container>
  <div class=no_comments>
  <p>
  No comments <br />
  to view... <br />
  <span id=yet> YET! </span><br />
  Join a Group,<br />
  make some <br /> Movie Friends!
  </p>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: "Name", class: 'session' %><br />
  <%= f.password_field :password, placeholder: "Password", class: 'session' %><br />
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'session' %><br /><br />
  <%= f.file_field :picture, id: :user_picture %>
  <%= f.submit "Sign Up", class: 'session'  %>
<% end %>

app/views/users/_lil_logo.html.erb
<div class=lil_logo_container>
<div class=lil_logo>
<%= render 'logo' %>
</div>
</div>

app/views/users/_menu.html.erb
<div class="menu">
  <%= link_to "Home", home_path, id: 'menu_home'%> |
  <%= link_to "Movies", movies_path, id: 'menu_movies'%> |
  <%= link_to "Groups", groups_path, id: 'menu_groups' %> |
  <%= link_to "Sign Out", logout_path, id: 'menu_signout' %>
</div>

app/views/users/home.html.erb
<!-- congratulations you fucking did it you logged in
<%= link_to "Logout", logout_path %> -->
<%= render 'lil_logo' %>
<%= render 'menu' %>
<%= render 'comments' %>

<div class=message>
<% if flash[:error] %>
  <%flash[:error].each do |message|%>
    <%= message %></br>
  <% end %>
<% end %>
</div>

<div class='content'>

  <div id='home_userimage'>
    <% if @user.picture.present? %>
     <%= image_tag(@user.picture_url, width: '70%') %>
   <% else %>
     <%= image_tag("gen_user_pic.gif", :alt => "Upload a picture!") %>
   <% end %>
 </div>
  <br /><div id='home_welcome'>
  <span id='home_username'>Welcome,</span>
  <span id='home_username'><%= link_to @user.name, user_path(@user) %>!</span>
</div><br />

</div>


<!-- <%= render 'lil_logo' %>
<%= render 'menu' %>
<%= render 'comments' %>

<div class='content'>

</div> -->

app/views/users/new.html.erb
<%= render 'logo' %>

<div class=message>
<% if flash[:error] %>
  <%flash[:error].each do |message|%>
    <%= message %></br>
  <% end %>
<% else %>
Cool! New Friend!
<% end %>
</div>

<div class=form_class>
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<%= render 'lil_logo' %>
<%= render 'menu' %>
<!-- render 'comments' BROKEN -->

<div class='content'>
  <%= @user.name %><br />
  <% if @user.picture.present? %>
   <%= image_tag(@user.picture_url, width: '70%') %>
 <% else %>
   <%= image_tag("gen_user_pic.gif", :alt => "Upload a picture!") %>
 <% end %>

 <div class=message>
 <% if flash[:error] %>
   <%flash[:error].each do |message|%>
     <%= message %></br>
   <% end %>
 <% end %>
 </div>

<% if @user == current_user %>
Edit your account:<br /><br />
  <%= form_for @user do |f| %>
    <%= f.text_field :name, placeholder: @user.name %><br />
    <%= f.password_field :password, value: nil, placeholder: "password" %><br />
    <%= f.file_field :picture, id: :user_picture %><br />
    <%= f.submit  %>
  <% end %>
<% end %>


</div>

<!-- stats on user -->
<div class='all_comments'>
  <%= plant_trees_for @comments %>
<div>